"""change user - cart relationship

Revision ID: 01438255f572
Revises: d4fb9003e246
Create Date: 2026-07-22 19:29:28.256973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01438255f572'
down_revision: Union[str, Sequence[str], None] = 'd4fb9003e246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'carts', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='unique')
    # ### end Alembic commands ###
