"""add public_id to product model

Revision ID: d4fb9003e246
Revises: 2d21789613d0
Create Date: 2026-07-22 18:27:28.213062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fb9003e246'
down_revision: Union[str, Sequence[str], None] = '2d21789613d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_public_id', sa.String(), nullable=False))
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'image_public_id')
    # ### end Alembic commands ###
